# **IMPORTING LIBRARIES**

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# **IMPORTING DATASET**

In [2]:
dataset = pd.read_csv('Data.csv')

In [4]:
 X = dataset.iloc[:, :-1].values #creating the independent variable

In [6]:
Y = dataset.iloc[:, -1].values #creating the depenedent variable

In [2]:
print(X)

NameError: name 'X' is not defined

In [8]:
print(Y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


# **TAKING CARE OF THE MISSING DATA**


In [11]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

In [12]:
imputer.fit(X[:, 1:]) #calculating the missing data

SimpleImputer()

In [13]:
#tranforming the data matrix with the calculated missing data
X[:, 1:] = imputer.transform(X[:, 1:])

In [14]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


# ENCODING THE CATEGORICAL DATA

In [ ]:
# from sklearn.compose import ColumnTransformer #importing columntranforming
from sklearn.preprocessing import OneHotEncoder #importing Encoding

In [18]:
#creating an object of the ColumnTranformer class
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')

In [19]:
#fitting and tranforming the dataset matrix
X = np.array(ct.fit_transform(X))

In [20]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [21]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y = le.fit_transform(Y)

In [22]:
print(Y)

[0 1 0 0 1 1 0 1 0 1]


# SPLITTING THE DATASET

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state = 1)

In [24]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [25]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [26]:
print(Y_train)

[0 1 0 0 1 1 0 1]


In [27]:
print(Y_test)

[0 1]


# FEATURE SCALING
**HERE WE ARE ONLY DISCUSSING ABOUT THE STANDARDISATION TECHNIQUE**


In [30]:
from sklearn.preprocessing import StandardScaler
stdscl = StandardScaler()
X_train[:, 3:] = stdscl.fit_transform(X_train[:, 3:])
X_test[:, 3:] = stdscl.fit_transform(X_test[:, 3:])

In [31]:
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578554 -1.0781259408412427]
 [0.0 1.0 0.0 -0.014117293757057846 -0.07013167641635404]
 [1.0 0.0 0.0 0.5667085065333239 0.6335624327104546]
 [0.0 0.0 1.0 -0.3045301939022487 -0.307866172742979]
 [0.0 0.0 1.0 -1.901801144700799 -1.4204636155515822]
 [1.0 0.0 0.0 1.1475343068237056 1.2326533634535488]
 [0.0 1.0 0.0 1.4379472069688966 1.5749910381638883]
 [1.0 0.0 0.0 -0.7401495441200352 -0.5646194287757336]]


In [ ]:
print(X_test)